// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmcydovbgswdxwuqbokb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtY3lkb3ZiZ3N3ZHh3dXFib2tiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzg1MjgsImV4cCI6MjA3Mzc1NDUyOH0.9EXH3yChJV4ESxV6Ea0s5UbIQ0UQ9ntTLfifEmpPqWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});